backend:
  name: git-gateway
  branch: main # Or the branch you are working on

media_folder: "assets/uploads" # Where to store uploaded files
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Page Content"
    files:
      - file: "_data/main.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "SEO & General", name: "general", widget: "object", fields: [
              { label: "Site Title", name: "site_title", widget: "string", hint: "The title that appears in the browser tab." },
              { label: "CV File", name: "cv_url", widget: "file", media_folder: "assets/documents", public_folder: "/assets/documents", hint: "Upload your CV here (PDF recommended)." }
            ]}
          - { label: "Hero Section", name: "hero", widget: "object", fields: [
              { label: "Name", name: "name", widget: "string", hint: "Your full name, e.g., MOHAMED EZZAT" },
              { label: "Title", name: "title", widget: "string", hint: "Your professional title or headline." },
              { label: "Description", name: "description", widget: "text", hint: "A brief, engaging summary of your professional value." }
            ]}
          - { label: "About Section", name: "about", widget: "object", fields: [
              { label: "Title", name: "title", widget: "string", default: "About Me" },
              { label: "Content", name: "content", widget: "markdown", hint: "A more detailed paragraph about your background and passion." }
            ]}
          - { label: "Work Experience", name: "experience", widget: "object", fields: [
              { label: "Title", name: "title", widget: "string", default: "Work Experience" },
              { label: "Jobs", name: "jobs", widget: "list", fields: [
                  { label: "Job Title", name: "title", widget: "string" },
                  { label: "Employment Period", name: "date", widget: "string", hint: "e.g., 2023 - Present" },
                  { label: "Responsibilities", name: "responsibilities", widget: "list", field: { label: "Responsibility", name: "item", widget: "string" } }
              ]}
            ]}
          - { label: "Skills & Expertise", name: "skills", widget: "object", fields: [
              { label: "Title", name: "title", widget: "string", default: "Skills & Expertise" },
              { label: "Skill List", name: "skill_list", widget: "list", field: { label: "Skill", name: "name", widget: "string" } }
            ]}
          - { label: "Education & Certifications", name: "education", widget: "object", fields: [
              { label: "Title", name: "title", widget: "string", default: "Education & Certifications" },
              { label: "Institution Name", name: "institution", widget: "string", hint: "e.g., The Higher Institute of E-Commerce Systems" },
              { label: "Description", name: "description", widget: "markdown" },
              { label: "Certifications Title", name: "cert_title", widget: "string", default: "Certificates and Courses" },
              { label: "Certificates", name: "certificates", widget: "list", field: { label: "Certificate", name: "name", widget: "string" } }
            ]}
          - { label: "Contact Section", name: "contact", widget: "object", fields: [
              { label: "Title", name: "title", widget: "string", default: "Get In Touch" }
            ]}
          - { label: "Footer", name: "footer", widget: "object", fields: [
              { label: "Copyright Text", name: "copyright", widget: "string", hint: "e.g., 2025 Mohamed Ezzat. All Rights Reserved." },
              { label: "Social Links", name: "social_links", widget: "list", fields: [
                  { label: "Icon (Font Awesome)", name: "icon", widget: "string", hint: "e.g., fab fa-linkedin-in" },
                  { label: "URL", name: "url", widget: "string" },
                  { label: "Aria Label", name: "label", widget: "string", hint: "For accessibility, e.g., LinkedIn" }
              ]}
            ]}
