backend:
  name: git-gateway
  branch: main # Or the branch you are working on

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_data/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Hero Section", name: "hero", widget: "object", fields: [
          { label: "Name", name: "name", widget: "string", default: "Ezzat Al-Sayed" },
          { label: "Title", name: "title", widget: "string", default: "Frontend Developer" },
          { label: "Description", name: "description", widget: "markdown" }
        ]}
      - { label: "About Section", name: "about", widget: "object", fields: [
          { label: "Title", name: "title", widget: "string", default: "About Me" },
          { label: "Content", name: "content", widget: "markdown" }
        ]}
      - { label: "Work Experience", name: "experience", widget: "object", fields: [
          { label: "Title", name: "title", widget: "string", default: "Work Experience" },
          { label: "Jobs", name: "jobs", widget: "list", fields: [
              { label: "Job Title", name: "title", widget: "string" },
              { label: "Date Range", name: "date", widget: "string" },
              { label: "Responsibilities", name: "responsibilities", widget: "list", field: { label: "Responsibility", widget: "string"} }
          ]}
        ]}
      - { label: "Skills & Expertise", name: "skills", widget: "object", fields: [
          { label: "Title", name: "title", widget: "string", default: "Skills & Expertise" },
          { label: "Skill List", name: "skill_list", widget: "list", field: { label: "Skill", widget: "string"} }
        ]}
      - { label: "Education & Certifications", name: "education", widget: "object", fields: [
          { label: "Title", name: "title", widget: "string", default: "Education & Certifications" },
          { label: "Institution Name", name: "institution", widget: "string" },
          { label: "Description", name: "description", widget: "markdown" },
          { label: "Certifications Title", name: "cert_title", widget: "string" },
          { label: "Certificates", name: "certificates", widget: "list", field: { label: "Certificate", widget: "string"} }
        ]}
      - { label: "Contact Section", name: "contact", widget: "object", fields: [
          { label: "Title", name: "title", widget: "string", default: "Get In Touch" }
        ]}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General"
        name: "general"
        file: "_data/settings.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "CV File URL", name: "cv_url", widget: "string" }
      - label: "Footer"
        name: "footer"
        file: "_data/footer.json"
        fields:
          - { label: "Copyright Text", name: "copyright", widget: "string" }
          - { label: "Social Links", name: "social_links", widget: "list", fields: [
              { label: "Aria Label", name: "label", widget: "string" },
              { label: "URL", name: "url", widget: "string" },
              { label: "Font Awesome Icon", name: "icon", widget: "string" }
            ]}
